openscilab/memor

- .github/dependabot.yml
- CHANGELOG.md
> Version 0.1

- memor/__init__.py
- memor/session.py
- tests/test_prompt_template.py
- `Session` class structure added
> Session Structure

- memor/functions.py
- memor/params.py
- memor/session.py
- `Session` class `render` method added
- Minor edits
> `Session` render

- README.md
- memor/__init__.py
- memor/functions.py
- memor/params.py
- memor/prompt.py
- memor/response.py
- memor/session.py
- memor/template.py
- tests/test_prompt.py
This PR fixes some name inconsistency, renamed `PromptRenderFormat` to `RenderFormat`, and the function for `render` method for `Response`.
I'm not sure if you like the changes about the render though. Let me know if you like it.
> Refactor: `validation` and `Response`.`render` function

- README.md
- memor/prompt.py
- memor/response.py
- memor/session.py
- memor/template.py
- tests/test_prompt_template.py
- tests/test_response.py
- `Template`, `Response`, `Prompt` and `Session` classes JSON functions refactored
> JSON functions

- memor/session.py
- `Session` class properties added
> Session properties

- memor/functions.py
- memor/params.py
- tests/test_prompt.py
- tests/test_prompt_template.py
- tests/test_response.py
- tests/test_session.py
> Tests Modification

- CHANGELOG.md
- README.md
- memor/functions.py
- memor/prompt.py
- tests/test_response.py
- `CHANGELOG.md` updated
- `README.md` updated
> Minor edits

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
> Version 0.2

- CHANGELOG.md
- memor/session.py
- tests/test_session.py
- `Session` class `__len__` method added
> Session Length

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
fix #59 
fix #60 
fix #66 
Version 0.3
> Version 0.3

- CHANGELOG.md
- README.md
- memor/response.py
- memor/template.py
- tests/test_response.py
#63 
- `inference_time` parameter added to `Response` class
- `README.md` updated
- Test system modified
> Inference Time

- CHANGELOG.md
- memor/session.py
- tests/test_session.py
- `Session` class `__contains__` method added
> Session `__contains__` method

- CHANGELOG.md
- memor/response.py
- tests/test_response.py
- `Response` class `__len__` method added
> Response `__len__`

- CHANGELOG.md
- memor/functions.py
- memor/prompt.py
- memor/response.py
- memor/session.py
- memor/template.py
- otherfiles/version_check.py
- setup.py
#65 
This PR adds typing features to memor. It includes typings for function parameters and output.
Also the part of doc-string which is no linger needed remvoed.
> Typing Feature Added

- CHANGELOG.md
- memor/prompt.py
- memor/session.py
- tests/test_prompt.py
- `Prompt` class `__len__` method
> Prompt `__len__`

- CHANGELOG.md
- memor/prompt.py
- memor/response.py
- tests/test_prompt.py
- `Prompt` class default values updated
- `Response` class default values updated
> Default Value

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
fix #63 
fix #64 
fix #65 
Version 0.4
> Version 0.4

- CHANGELOG.md
- memor/session.py
- tests/test_session.py
- `Session` class `clear_messages` method added
> Clear messages

- CHANGELOG.md
- README.md
#68 
This PR adds the details of `PresetPromptTemplate` to readme, making it more readable and accessible for users.
> Prompt Template Details Added to README.md

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
fix #67 
fix #68 
fix #79 
Version 0.5
> Version 0.5

- CHANGELOG.md
- memor/__init__.py
- memor/params.py
- memor/response.py
- tests/test_prompt.py
- tests/test_response.py
#92 
An enum for LLM models has been added. I tried to cover well-known temporary LLMs.
> LLM Model Enum

- .gitignore
- CHANGELOG.md
- memor/functions.py
- memor/params.py
- memor/response.py
- tests/test_response.py
#86 
- `Response` class `id` property added
> Response ID

- CHANGELOG.md
- memor/session.py
- tests/test_session.py
#86 
- `Session` class `remove_message_by_index` and `remove_message_by_id` methods added
- `Session` class `get_message_by_index`, `get_message_by_id` and `get_message` methods added
- Test system modified
- `Session` class `remove_message` method modified
> ID Methods

- CHANGELOG.md
- memor/prompt.py
- memor/response.py
- tests/test_prompt.py
- tests/test_response.py
- `Response` class `regenerate_id` method added
- `Prompt` class `regenerate_id` method added
> Regenerate

- CHANGELOG.md
- memor/prompt.py
- memor/response.py
- memor/session.py
- memor/template.py
- Modification handling centralized via `_mark_modified` method
> Mark Modified

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
fix #86 
fix #91 
fix #92 
fix #100 
Version 0.6
> Version 0.6

- CHANGELOG.md
- memor/params.py
- memor/prompt.py
- memor/response.py
- tests/test_prompt.py
- tests/test_response.py
#100 
- `AI_STUDIO` render format modified
> AI Studio Warning

- CHANGELOG.md
- memor/session.py
- tests/test_session.py
- `Session` class messages status bug fixed
> Messages Status Bug

- .gitignore
- CHANGELOG.md
- memor/prompt.py
- memor/response.py
- memor/session.py
- memor/template.py
- tests/test_prompt.py
- tests/test_prompt_template.py
- tests/test_response.py
- tests/test_session.py
#85 
- `Session` class `get_size` method
- `Response` class `get_size` method
- `Prompt` class `get_size` method
- `PromptTemplate` class `get_size` method
- `Session` class `size` attribute
- `Response` class `size` attribute
- `Prompt` class `size` attribute
- `PromptTemplate` class `size` attribute
> `size` attributes and `get_size` method added to Memor objects

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
fix #84 
fix #85 
fix #115 
fix #116 
Version 0.7
> Version 0.7

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- README.md
- SECURITY.md
- memor/params.py
- otherfiles/meta.yaml
- otherfiles/version_check.py
- setup.py
fix #131 
fix #130 
fix #69 
fix #135 
fix #134 
fix #144 
fix #138 
Version 0.8
> Version 0.8
